{ config, pkgs, home-manager, attrs, ... }:
{
  imports = [
    home-manager.nixosModules.home-manager
  ];


  home-manager.users.mrwbarg = {
    home.packages = with pkgs; [
      kitty
      waybar
      dunst
      swww
      networkmanagerapplet
      gnome.nautilus
      pkgs.nerdfonts
    ];

    wayland.windowManager.hyprland = {
      enable = true;
      systemd.enable = true;
      settings = {
        autogenerated = 0;
        "$mod" = "SUPER";
        bind = [
          # programs
          "$mod, Q, exec, kitty"
          "$mod, W, killactive"
          "$mod, O, exit"
          "$mod, E, exec, nautilus"
          ''$mod, SPACE, exec, rofi -show drun -show-icons -theme-str '@import "catppuccin-mocha.rasi"' ''

          # workspaces
          "$mod, H, workspace, -1"
          "$mod, L, workspace, +1"
          "$mod, left, workspace, -1"
          "$mod, right, workspace, +1"

          "$mod ALT, H, movefocus, l"
          "$mod ALT, J, movefocus, u"
          "$mod ALT, K, movefocus, d"
          "$mod ALT, L, movefocus, r"
          "$mod ALT, left, movefocus, l"
          "$mod ALT, up, movefocus, u"
          "$mod ALT, down, movefocus, d"
          "$mod ALT, right, movefocus, r"


          "$mod SHIFT, H, movetoworkspace, -1"
          "$mod SHIFT, L, movetoworkspace, +1"
          "$mod SHIFT, left, movetoworkspace, -1"
          "$mod SHIFT, right, movetoworkspace, +1"
        ];
        input = {
          kb_layout = "br";
          kb_variant = "nodeadkeys";
        };
        monitor = ",preferred,auto,1.25";
        exec-once = [
          "waybar"
          "dunst"
          "hyprctl setcursor catppuccin-mocha-dark-cursors 24"
        ];
      };
    };
  };
}
